{ body = None Text
, status_code = None (List Natural)
, client_cert = None Text
, headers = None Text
, dest = None Text
, follow_redirects = None Text
, force_basic_auth = None Text
, removes = None Text
, method = None Text
, creates = None Text
, user = None Text
, timeout = None Natural
, others = None Text
, body_format = None Text
, return_content = None Text
, password = None Text
, validate_certs = None Text
, HEADER_ = None Text
, client_key = None Text
}
