{ attributes = None Text
, copy = None Bool
, creates = None Text
, decrypt = None Bool
, exclude = None (List Text)
, extra_opts = None (List Text)
, group = None Text
, include = None (List Text)
, io_buffer_size = None Natural
, keep_newer = None Bool
, list_files = None Bool
, mode = None Text
, owner = None Text
, remote_src = None Bool
, selevel = None Text
, serole = None Text
, setype = None Text
, seuser = None Text
, unsafe_writes = None Bool
, validate_certs = None Bool
}