{ remote_src = None Bool
, exclude = None (List Text)
, setype = None Text
, unsafe_writes = None Bool
, selevel = None Text
, list_files = None Bool
, extra_opts = None (List Text)
, decrypt = None Bool
, attributes = None Text
, seuser = None Text
, owner = None Text
, mode = None Text
, copy = None Bool
, serole = None Text
, validate_certs = None Bool
, keep_newer = None Bool
, group = None Text
, creates = None Text
}